/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'i068969' at '8/31/15 6:02 PM' with Gradle 2.4
 *
 * @author i068969, @date 8/31/15 6:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
